#spring:
#data:
#mongodb:
#host: mongodb.tacocloud.com
#port: 27018
#username: tacocloud
#password: s3cr3tp455w0rd
#database: tacoclouddb


#logging:
#level:
#tacos: DEBUG
#---
#spring:
#  profiles: prod
#  datasource:
#  url: jdbc:mysql://localhost/tacocloud
#  username: tacouser
#  password: tacopassword
#  logging:
#  level:
#  tacos: WARN

management:
  endpoints:
    web:
      exposure:
        include: '*'

#DeV embedded mongoDb
spring:
  application:
    name: employeeService
  data:
    mongodb:
      host: localhost
      database: employeeServiceDb
      port: 12345

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/, another